### ISSUE TITLE
Deploy prototype to LINCC HUB

### ISSUE THREAD

**Issue by delucchi-cmu** [astronomy-commons/lsd2#8]
Steps needed:
1.a. get the repo in a pip/conda installable state
OR 1.b. just install from source 
2.a. update prototype to read partitions from s3 buckets, and load partitioned GAIA into s3 buckets
OR 2.b. get a smaller (e.g. narrower) version of GAIA that can fit on the existing posix allotment for lincc hub
3. documentation for how the first two steps were done and could be reproduced
4. example notebook

**Comment by nevencaplar** [comment]
closing, completed with ADASS tutorial
